# Generated by Django 5.1 on 2024-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mydata',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
